version: '3.7'

services:

    sysmonitor_api:
      image: sysmonitor_api
      container_name: sysmonitor_api
      build:
        context: ../.
        dockerfile: ./deployments/docker/server.Dockerfile    
      environment:
        TZ: Europe/Samara 
      ports:
        - "50051:50051"
      expose:
        - 50051
      networks:
        - net
      restart: on-failure 

    integration_tests:
      image: integration_tests
      container_name: integration_tests
      build:
        context: ../.
        dockerfile: ./deployments/docker/integration-test/Dockerfile
      command: "true"
      environment:
        GRPC_LISTEN: "sysmonitor_api:50051"
        QUERY_TIMEOUT: 10
        QUERY_PERIOD: 15
        TZ: Europe/Samara        
      depends_on:
        - sysmonitor_api
      restart: on-failure
      networks:
        - net      

networks:
  net:
    name: net
    driver: bridge