language: go

go:
    - 1.14.x

before_install:
    - sudo apt-get update
    - sudo apt-get -y install sysstat     
    - go get -d -v ./cmd/sysmonitor

install: true

notifications:
    email:
      on_failure: always

before_script:
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $GOPATH/bin v1.25.1
    
script:
    - golangci-lint run
    - make test