language: go

go:
    - 1.14.x

before_install:
    go get -d -v

install: true

notifications:
    email:
      on_success: change
      on_failure: always

script:
    - go test -race -count 100 ./...