# Пример файла конфигурации для сервиса "Системный мониторинг"

# Настройки grpc-сервера    
# host и port на котором должен работать gRPC-сервер
host: ""
port: "50055"

# Настройки логирования
log: 
  # уровень логирования (error / warn / info / debug)
  level: debug
  # путь к файлу логов
  file: sysmonitor.log
  # формат логирования
  format_JSON: false

# Настройка подсистемы сбора статистики
collector:
    # Частота выполнения сбора статистики в секундах
    timeout: 5
    # виды сбора статистики: load_system, load_cpu, load_disk, top_talkers, network_stat
    category:
      load_system: true
      load_cpu: true
      load_disk: true
      top_talkers: true
      network_stat: true
